var otpRepo = require('../repos/otpRepo');
const nodemailer = require("nodemailer");
var express = require('express'),
    utils = require('../fn/utils');
let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: utils.mail.user, // generated ethereal user
        pass: utils.mail.pass// generated ethereal password
    }
});

var router = express.Router();
router.post('/:email', (req, res) => {
    email = req.params.email;
    otp = Math.floor(Math.random() * (999999 - 100000 + 1)) + 100000;
    let mailOptions = {
        from: 'xuanbachpg@gmail.com',
        to: email,
        subject: 'One Time Password (OTP) confirmation- Internet banking',
        text: 'Dear Sir/Madam , \n' + 'Please use the following OTP: ' + otp + ' to complete your online request \n'
            + 'This code will expire five mins after this email was sent \n'
            + 'This email is automatically generated by the BBD Bank online. Please do not reply to this email. '
    };
    otpRepo.load(email).then(rows => {
        return rows;
    }).then(rows => {
        if (0 == rows.length) {
            otpRepo.add(email, otp).then(insertId => {

                transporter.sendMail(mailOptions, (err, data) => {
                    if (err) {
                        console.log(err);
                        return res.status(400).json({
                            message: "bad request"
                        });
                    }
                    return res.status(200).json({
                        message: "send mail success"
                    });
                });
            }).catch(error => {
                console.log(error);
                res.status(500).json({
                    message: "view log on console"
                });
            })
        }
        else {
            otpRepo.update(email, otp).then(changedRows => {
                if (changedRows) {
                    transporter.sendMail(mailOptions, (err, data) => {
                        if (err) {
                            console.log(err);
                            return res.status(400).json({
                                message: "bad request"
                            });
                        }
                        return res.status(200).json({
                            message: "send mail success"
                        });
                    });
                }
                else {
                    console.log("thêm email vào db k thành công");
                    return res.status(500).json({
                        message: "view log on console"
                    });
                }
            }).catch(error => {
                console.log(error);
                res.status(500).json({
                    message: "view log on console"
                });
            })
        }
    })


});

module.exports = router;